build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php: {  }

tools:
  php_code_coverage:
    enabled: true
  external_code_coverage:
    timeout: 600
    #timeout: 600 # There can be another pull request in progress
  #runs: 4 # ( PHP 7.1 + 7.2 ) *2