language: php
sudo: false

jobs:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.1'
      env: deps=low
    - php: '7.2'
      env: deps=low
  fast_finish: true

before_install:
#  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - if [[ $deps = 'low' ]]; then
      composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;
    else
      cat composer.json | python3 -c "import json,sys;obj=json.load(sys.stdin);print(' '.join(obj['suggest'].keys()))" | xargs composer require
      && composer update --prefer-dist --no-progress --no-suggest --ansi;
    fi

script:
    - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - if [ $deps != 'low' ]; then
      wget https://scrutinizer-ci.com/ocular.phar
      && php ocular.phar code-coverage:upload --format=php-clover --revision=$TRAVIS_COMMIT coverage.clover;
    fi
  #- php vendor/bin/php-coveralls -v